# -*- coding: utf-8 -*-
"""HW1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYpNGSbFFSkLZNKXwpi1u-ZYmatacYR6
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/DATA/olympic_medals.csv")

## part (a)
dfSize = df.size              # the total number of elements in the dataframe
dfRows = df.shape[0]          # the total number of rows in dataframe
dfColums = df. shape[1]       # the total number of rows in the dataframe

## part (b)
dfDatatypes = df.dtypes       # the datatypes of the different columns

## part (c)
uniquelocation = len(df["Location"].unique())    # df["location"] returns the column under "location", unique()
                                                 # function only returns unique values and len() calculates
                                                 # the total number of unique cities.


## part (d)
usaWin = len(df[df["Location"] == "USA"])   # filter rows where Country is USA and count the number of rows

## part (e)
medalsPerNationality = df.groupby("Location").size()   # group data by Country and count the number of occurences

## print output
print("Size:", dfSize)
print("Rows:", dfRows)
print(dfDatatypes)
print(uniquelocation)
print(usaWin)
print(medalsPerNationality)